(require 'package)

;;--- General Setup --------------------------------------------------

;; Add additional repositories.
(add-to-list 'package-archives '("melpa-stable" . "https://stable.melpa.org/packages/") t)

;; https://www.gnu.org/software/emacs/manual/html_node/emacs/Package-Installation.html
;;
;; To keep Emacs from automatically making packages available at
;; startup, change the variable package-enable-at-startup to nil. You
;; must do this in the early init file, as the variable is read before
;; loading the regular init file. Currently this variable cannot be
;; set via Customize.
;;
;; If you have set package-enable-at-startup to nil, you can still
;; make packages available either during or after startup. To make
;; installed packages available during startup, call the function
;; package-activate-all in your init file. To make installed packages
;; available after startup, invoke the command M-:
;; (package-activate-all) RET.
(setq package-enable-at-startup nil)
(package-initialize)

;; https://www.gnu.org/software/emacs/manual/html_node/emacs/Saving-Customizations.html
;;
;; Store settings generated by the customize interface in a separate
;; file.
(setq custom-file (concat user-emacs-directory "custom.el"))
(when (file-exists-p custom-file)
  (load custom-file))

;; Bootstrap 'use-package'. 
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(eval-when-compile
  (require 'use-package))

;;--- Load Packages --------------------------------------------------

;; Vim key bindings in Emacs.
(use-package evil
  :ensure t
  :init
  (setq evil-want-integration t)
  (setq evil-want-keybinding nil)
  :config
  (evil-mode 1))
(use-package evil-escape
  :after evil
  :ensure t
  :config
  (setq-default evil-escape-key-sequence "fd")
  (setq-default evil-escape-delay 0.1)
  (evil-escape-mode t))
(use-package evil-collection
  :after evil
  :ensure t
  :config
  (evil-collection-init))

;; Jumping with avy.
(use-package avy
  :ensure t
  :bind
  ("C-;" . avy-goto-char)
  ("C-'" . avy-goto-char-timer))

;; Git client.
(use-package magit
  :ensure t
  :bind
  ("C-x g" . magit-status))
(use-package evil-magit
  :ensure t)

;; Edit .tex files with AUCTex.
(use-package tex
  :defer t
  :ensure auctex
  :init
  ;; Parse file after loading it if no style hook is found for it.
  (setq TeX-parse-self t)
  ;;Automatically save style information when saving the buffer.
  (setq TeX-auto-save t))

;;--- Additional Configuration ---------------------------------------

;; Show column number.
(setq column-number-mode t)
